# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-21 04:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='user',
        ),
        migrations.AddField(
            model_name='trip',
            name='creator',
            field=models.ForeignKey(default=99, on_delete=django.db.models.deletion.CASCADE, related_name='createdtrips', to='travel.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='members',
            field=models.ManyToManyField(related_name='tripsjoined', to='travel.User'),
        ),
    ]
