# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-21 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_auto_20180521_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='travel_date_from',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='trip',
            name='travel_date_to',
            field=models.DateTimeField(),
        ),
    ]
